"""VFS protocol: abstract interface all backends must implement."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Iterator, Protocol, runtime_checkable


@dataclass
class VFSStat:
    """Minimal file metadata returned by VFSBackend.stat()."""

    size: int
    mtime: float
    is_dir: bool


class VFSError(Exception):
    """Raised when a VFS operation violates backend constraints (e.g. jail escape)."""


@runtime_checkable
class VFSBackend(Protocol):
    """Protocol that all VFS backends must satisfy."""

    name: str

    def read_text(self, path: str, *, encoding: str = "utf-8") -> str: ...
    def read_bytes(self, path: str) -> bytes: ...
    def write_text(self, path: str, content: str, *, encoding: str = "utf-8") -> int: ...
    def write_bytes(self, path: str, content: bytes) -> int: ...
    def exists(self, path: str) -> bool: ...
    def is_file(self, path: str) -> bool: ...
    def is_dir(self, path: str) -> bool: ...
    def list_dir(self, path: str) -> list[str]: ...
    def remove(self, path: str) -> None: ...
    def rename(self, src: str, dst: str) -> None: ...
    def stat(self, path: str) -> VFSStat: ...
    def glob(self, pattern: str, *, root: str = ".") -> list[str]: ...
    def walk(self, root: str) -> Iterator[tuple[str, list[str], list[str]]]: ...
