"""Provider abstraction: canonical types and the ``Provider`` base class.

This module defines the **provider-agnostic contract** that the agent loop
talks to. Concrete adapters (Anthropic, OpenAI, Gemini, Ollama, ...) live in
sibling modules and translate these canonical types to/from each vendor SDK.

The canonical surface is:

- :class:`Message` — one turn of the conversation.
- :class:`ToolCall` — a tool invocation requested by the model.
- :class:`Usage` — token accounting per turn.
- :class:`StreamChunk` — a single event from :meth:`Provider.stream`.
- :class:`Provider` — the abstract base class every adapter implements.
- :class:`ProviderError` — raised on unrecoverable provider failures.
"""
from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, AsyncIterator, Literal

from pydantic import BaseModel, Field


Role = Literal["system", "user", "assistant", "tool"]


class ToolCall(BaseModel):
    """A single tool call requested by the model.

    Attributes:
        id: Provider-issued identifier. Used to match the tool result back to
            this call when the next turn is sent. Some providers (e.g. Gemini)
            don't issue an id natively — the adapter generates one.
        name: Registered tool name (matches a key in
            :data:`vulpcode.tools.base.TOOL_REGISTRY`).
        arguments: Decoded JSON arguments. Empty dict if the model issued no
            arguments.
    """

    id: str
    name: str
    arguments: dict[str, Any] = Field(default_factory=dict)


class Message(BaseModel):
    """One turn of the conversation in canonical form.

    Adapters convert this into the vendor-native shape and back. The system
    prompt is **not** part of the message list — it is passed separately to
    :meth:`Provider.stream` via the ``system`` argument.

    Attributes:
        role: One of ``"system"``, ``"user"``, ``"assistant"``, ``"tool"``.
        content: Either a plain string (the common case) or a list of content
            blocks (used for multimodal input — images, etc.).
        tool_calls: For ``role="assistant"`` turns where the model requested
            tool execution. ``None`` when no tools were called.
        tool_call_id: For ``role="tool"`` turns: the id of the
            :class:`ToolCall` this message answers.
        name: Optional tool name, used by some providers when echoing tool
            results back into the conversation.
    """

    role: Role
    content: str | list[dict[str, Any]] = ""
    tool_calls: list[ToolCall] | None = None
    tool_call_id: str | None = None
    name: str | None = None


class Usage(BaseModel):
    """Token accounting for a single turn.

    Cache fields are only populated by providers that surface prompt-cache
    accounting (currently Anthropic). Other providers leave them at zero.

    Attributes:
        input_tokens: Tokens consumed from the prompt.
        output_tokens: Tokens generated by the model.
        cache_read_tokens: Prompt tokens served from a cache hit.
        cache_creation_tokens: Prompt tokens written into the cache.
    """

    input_tokens: int = 0
    output_tokens: int = 0
    cache_read_tokens: int = 0
    cache_creation_tokens: int = 0


ChunkType = Literal[
    "text",
    "tool_call",
    "tool_call_delta",
    "stop",
    "usage",
    "error",
]


class StreamChunk(BaseModel):
    """A single event emitted during :meth:`Provider.stream`.

    The adapter funnels every vendor-native event into one of these shapes so
    the agent loop is provider-agnostic.

    Attributes:
        type: Event kind. One of:

            - ``"text"`` — incremental text delta in :attr:`delta`.
            - ``"tool_call"`` — fully-formed tool call in :attr:`tool_call`.
            - ``"tool_call_delta"`` — partial tool-call payload (rare; most
              adapters buffer and emit ``"tool_call"`` once complete).
            - ``"stop"`` — turn ended; :attr:`stop_reason` may carry the
              reason (``"end_turn"``, ``"tool_use"``, ``"max_tokens"``, ...).
            - ``"usage"`` — token accounting in :attr:`usage`.
            - ``"error"`` — recoverable error in :attr:`error`.
        delta: Text delta when ``type="text"``.
        tool_call: Parsed tool call when ``type="tool_call"``.
        usage: Token usage when ``type="usage"``.
        error: Error message when ``type="error"``.
        stop_reason: Reason the model stopped, when ``type="stop"``.
        raw: Original vendor-native event (debug / pass-through).
    """

    type: ChunkType
    delta: str | None = None
    tool_call: ToolCall | None = None
    usage: Usage | None = None
    error: str | None = None
    stop_reason: str | None = None
    raw: dict[str, Any] | None = None


class ProviderError(RuntimeError):
    """Raised on unrecoverable provider failures.

    Examples include missing API keys, repeated 5xx responses, malformed
    upstream payloads, or transport-level errors that exhausted retries.
    """


class Provider(ABC):
    """Abstract base class for all model providers.

    Subclasses translate the canonical :class:`Message` / tool schema into the
    provider-native format and stream back :class:`StreamChunk` events. The
    agent loop never depends on any vendor SDK directly — it talks to this
    interface only.

    Attributes:
        name: Class-level provider identifier (e.g. ``"anthropic"``,
            ``"openai"``, ``"gemini"``). Used by the registry and logs.
        api_key: API key passed at construction (may be ``None`` for local
            providers like Ollama).
        base_url: Endpoint override. ``None`` falls back to the SDK default.
        timeout: Per-request timeout in seconds.
        extra: Any extra kwargs accepted by the constructor.
    """

    name: str

    def __init__(
        self,
        api_key: str | None = None,
        base_url: str | None = None,
        timeout: float = 120.0,
        **extra: Any,
    ) -> None:
        """Initialize the provider.

        Args:
            api_key: Provider API key. Optional for local providers (Ollama).
            base_url: Endpoint URL override. ``None`` uses the SDK default.
            timeout: Per-request timeout in seconds.
            **extra: Provider-specific extras; stored on ``self.extra``.
        """
        self.api_key = api_key
        self.base_url = base_url
        self.timeout = timeout
        self.extra = extra

    @abstractmethod
    async def stream(
        self,
        messages: list[Message],
        tools: list[dict[str, Any]],
        model: str,
        system: str | None = None,
        **kwargs: Any,
    ) -> AsyncIterator[StreamChunk]:
        """Stream a single turn of the conversation.

        The implementation MUST translate the canonical inputs into the vendor
        native format, call the streaming endpoint, and yield one
        :class:`StreamChunk` per logical event (text delta, tool call, usage,
        stop, error).

        Args:
            messages: Canonical message history (system prompt excluded).
            tools: List of canonical tool schemas — the form produced by
                :meth:`vulpcode.tools.base.Tool.to_schema`. The provider must
                translate these to its native format.
            model: Model id in provider-native form (e.g. ``"claude-sonnet-4-7"``,
                ``"gpt-4o"``, ``"gemini-2.0-flash"``).
            system: System prompt string. ``None`` means no system prompt.
            **kwargs: Provider-specific extras (``temperature``, ``max_tokens``,
                ``top_p``, ...). Adapters silently ignore unknown keys.

        Yields:
            :class:`StreamChunk` events in arrival order.

        Raises:
            ProviderError: On unrecoverable failures (auth, repeated 5xx,
                malformed upstream payload).
        """
        raise NotImplementedError
        yield  # pragma: no cover

    @abstractmethod
    def supports_tools(self) -> bool:
        """Whether the provider supports native tool calling.

        Returns:
            ``True`` if the provider understands the ``tools`` argument to
            :meth:`stream` natively. Providers returning ``False`` will see
            tool schemas dropped on the floor.
        """

    @abstractmethod
    def supports_vision(self) -> bool:
        """Whether the provider/model accepts image inputs.

        Returns:
            ``True`` if the adapter can pass image content blocks through to
            the model.
        """

    async def list_models(self) -> list[str]:
        """List models available to the configured account.

        Default implementation returns an empty list. Override when the
        underlying SDK exposes a model-listing endpoint.

        Returns:
            Model ids as the provider returns them.
        """
        return []

    async def aclose(self) -> None:
        """Release any underlying resources (HTTP clients, connections, ...).

        Default implementation is a no-op. Override when the adapter holds
        long-lived resources.
        """
        return None

    def __repr__(self) -> str:
        return f"<{type(self).__name__} name={self.name!r}>"
